src/Timewaster.Web/ViewModels/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Timewaster.Core.Entities.Accounts;
using Timewaster.Core.Entities.Boards;

namespace Timewaster.Web.ViewModels
{
    public class ProjectViewModel
    {
        public int? Id { get; set; }
        public string PartitionKey { get; set; }

        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public Sprint CurrentSprint { get; set; }
        public List<Sprint> Sprints { get; set; } = new List<Sprint>();
        public List<User> Users { get; set; } = new List<User>(); 
    }
}

src/Timewaster.Web/Controllers/PlansController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Timewaster.Core.Entities.Boards;
using Timewaster.Core.Interfaces.Services;
using Timewaster.Core.ValueObjects;
using Timewaster.Web.Converters;
using Timewaster.Web.ViewModels;

namespace Timewaster.Web.Controllers
{
    public class PlansController : Controller
    {
        private readonly IPlansService _plansService;

        public PlansController(IPlansService plansService)
        {
            _plansService = plansService;
        }

        public async Task<IActionResult> Index(int? id)
        {
            PlanViewModel viewModel = id == null
                ? PlansConverters.EntityToViewModel(
                   board: await _plansService.CreatePlan(new ServiceContext() { ContextId = "TEST" }),
                   statuses: await _plansService.GetDefaultStatuses(new ServiceContext())
                   )
                : PlansConverters.EntityToViewModel(
                    board: await _plansService.GetSprintPlan(new ServiceContext() { ContextId = "TEST" }, (int)id),
                    statuses: await _plansService.GetDefaultStatuses(new ServiceContext())
                    );
            return View(viewModel);
        }

        public async Task<IActionResult> CreateStory(StoryViewModel storyVM, int sprintId)
        {
            if (ModelState.IsValid)
            {
                Sprint sprint = await _plansService.GetSprint(new ServiceContext() { ContextId = "TEST" }, storyVM.SprintId);
                Story story = storyVM.ViewModelToEntity(sprint);
                
                await _plansService.CreateStory(new ServiceContext() { ContextId = "TEST" }, story);
                
                return RedirectToAction(nameof(Index), new { id = storyVM.SprintId });
            }
            storyVM.SprintId = sprintId;
            return View(storyVM);
        }

        public async Task<IActionResult> CreateIssue(IssueViewModel issueVM, int statusId, int storyId, int sprintId)
        {
            if (ModelState.IsValid)
            {
                Status status = await _plansService.GetStatus(new ServiceContext() { ContextId = "TEST" }, issueVM.StatusId);
                Story story = await _plansService.GetStory(new ServiceContext() { ContextId = "TEST" }, issueVM.StoryId);   
                Issue issue = issueVM.ViewModelToEntity(status, story);

                await _plansService.CreateIssue(new ServiceContext() { ContextId = "TEST" }, issue);
                
                return RedirectToAction(nameof(Index), new { id = issueVM.SprintId });
            }
            issueVM.StatusId = statusId;
            issueVM.StoryId = storyId;
            issueVM.SprintId = sprintId;
            return View(issueVM);
        }

        public async Task<IActionResult> UpdateStory([Bind("Name, Description")] Story story)
        {
            await _plansService.UpdateStory(new ServiceContext() { ContextId = "TEST" }, story);
            return View(story);
        }

        public async Task<IActionResult> UpdateIssue(int id, IssueViewModel issueVM)
        {
            if (id != issueVM.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                Status status = await _plansService.GetStatus(new ServiceContext() { ContextId = "TEST" }, issueVM.StatusId);
                Story story = await _plansService.GetStory(new ServiceContext() { ContextId = "TEST" }, issueVM.StoryId);
                Issue issue = issueVM.ViewModelToEntity(status, story);
                
                await _plansService.UpdateIssue(new ServiceContext() { ContextId = "TEST" }, issue);
                return RedirectToAction(nameof(Index), new { id = issueVM.SprintId });
            }

            return View(issueVM);
        }

        public async Task<IActionResult> DeleteSprint(int id)
        {
            await _plansService.DeleteSprint(new ServiceContext() { ContextId = "TEST" }, id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteStory(int id)
        {
            await _plansService.DeleteStory(new ServiceContext() { ContextId = "TEST" }, id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteIssue(int id)
        {
            await _plansService.DeleteIssue(new ServiceContext(), id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Timewaster.Web/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Timewaster.Core.Entities.Boards;
using Timewaster.Core.Entities.Projects;
using Timewaster.Core.Interfaces.Services;
using Timewaster.Core.ValueObjects;
using Timewaster.Web.ViewModels;

namespace Timewaster.Web.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IProjectService _projectService;

        public ProjectsController(IProjectService projectService)
        {
            _projectService = projectService;
        }

        public async Task<IActionResult> Index(int? id)
        {
            if (id == null) return NotFound();

            Project project = await _projectService.GetProject(new ServiceContext(), (int)id);
            Sprint currentSprint = project.Sprints.FirstOrDefault();
            project.Sprints.Remove(currentSprint);

            var projectViewModel = new ProjectViewModel
            {
                ProjectName = project.Name,
                CurrentSprint = currentSprint,
                Sprints = new List<Sprint>(project.Sprints),
            };
            return View(projectViewModel);
        }

        public async Task<IActionResult> Create([Bind("Name", "Description")] Project project)
        {
            if (!string.IsNullOrEmpty(project.Name))
            {
                project.PartitionKey = "test";
                project = await _projectService.CreateAsync(new ServiceContext(), project);
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

    }
}

src/Timewaster.Web/Views/Projects/Create.cshtml
@model Timewaster.Core.Entities.Projects.Project
@{
    ViewData["Title"] = "Create project";
}

<h4>Create</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateProject">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Dashboard</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Timewaster.Web/Views/Projects/Index.cshtml
@model Timewaster.Web.ViewModels.ProjectViewModel
@{
    ViewData["Title"] = Model.ProjectName;
}

<h4>@Model.ProjectName</h4>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm">
                    <h6>Sprints</h6>
                </div>
                <div class="col-sm">
                    <a class="border-dark" asp-area="" asp-controller="Plans" asp-action="Index">&#43; Add sprint</a>
                </div>
            </div>
            <div class="list-group">
                @if (Model.CurrentSprint != null)
                {
                    <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
                        <div class="d-flex justify-content-between">
                            <h5 class="mb-1">@Model.CurrentSprint?.ReferenceKey</h5>
                            <small>@Model.CurrentSprint?.CreatedAt.ToShortDateString() - @Model.CurrentSprint?.ClosingAt.ToShortDateString()</small>
                        </div>
                        <small>And some small print.</small>
                    </a>
                }
                else
                {
                    <small>No sprint defined yet.</small>
                }
                @foreach (var sprint in Model.Sprints)
                {
                    <a href="#" class="list-group-item list-group-item-action">
                        <div class="d-flex justify-content-between">
                            <h5 class="mb-1">@sprint.ReferenceKey</h5>
                            <small>@sprint.CreatedAt.ToShortDateString() - @sprint.ClosingAt.ToShortDateString()</small>
                        </div>
                        <small class="text-muted">And some muted small print.</small>
                    </a>
                }
            </div>       
        </div>
        <div class="col-sm-8">
            <div class="row">
                <div class="col-sm">
                    <h6>Stories</h6>
                </div>
                <div class="col-sm">
                    <h6>Add story</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <h6>Recent activities</h6>
                </div>
            </div>
        </div>
    </div>
</div>

src/Timewaster.Web/Views/Projects/View.cshtml
@model Timewaster.Web.ViewModels.ProjectViewModel

@{
    ViewData["Title"] = Model.ProjectName;
}

<h4>@Model.ProjectName</h4>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm">
                    <h6>Sprints</h6>
                </div>
                <div class="col-sm">
                    <h6>Add spring</h6>
                </div>
            </div>
            <div class="list-group">
                @if (Model.CurrentSprint != null)
                {
                    <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
                        <div class="d-flex justify-content-between">
                            <h5 class="mb-1">@Model.CurrentSprint?.ReferenceKey</h5>
                            <small>@Model.CurrentSprint?.CreatedAt.ToShortDateString() - @Model.CurrentSprint?.ClosingAt.ToShortDateString()</small>
                        </div>
                        <small>And some small print.</small>
                    </a>
                }
                else
                {
                    <small>No sprint defined yet.</small>
                }
                @foreach (var sprint in Model.Sprints)
                {
                    <a href="#" class="list-group-item list-group-item-action">
                        <div class="d-flex justify-content-between">
                            <h5 class="mb-1">@sprint.ReferenceKey</h5>
                            <small>@sprint.CreatedAt.ToShortDateString() - @sprint.ClosingAt.ToShortDateString()</small>
                        </div>
                        <small class="text-muted">And some muted small print.</small>
                    </a>
                }
            </div>       
        </div>
        <div class="col-sm-8">
            <div class="row">
                <div class="col-sm">
                    <h6>Stories</h6>
                </div>
                <div class="col-sm">
                    <h6>Add story</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <h6>Recent activities</h6>
                </div>
            </div>
        </div>
    </div>
</div>